name: 'PR Checks'

on:
  pull_request:
    branches:
    - "stg"
    - "dev"

env:
  UV_VERSION: 0.7.8 # Version of uv to install

jobs:
  uses: ./.github/workflows/reusable_wf.yml
  with:
      uv_version: ${{ env.UV_VERSION }}
